Fix Iris 1.7.0 support
Qendolin/better-clouds pull request #84
Opened 2024-04-25 17:49 UTC by iblowmymind

Fixes support for Iris 1.7.0's new class names after its refactor.
The mod's config page also has an issue with YACL >3.4.0 due to its new custom tab API, which would require a rewrite of it. I haven't been able to do anything about that as that is beyond me, so just consider either using YACL 3.3.1 or not opening the settings for the time being.

2024-04-25 19:41 UTC, iblowmymind commented
That's alright, please do let me know whenever you can!

2024-04-30 10:53 UTC, Qendolin requested changes
Looks good but you should still add the entry `"iris": "<1.7.0"` in the `breaks` section in `fabric.mod.json`.

2024-04-30 10:56 UTC, Qendolin approved these changes

2024-04-30 10:58 UTC, merged

2024-04-30 10:58 UTC, Qendolin commented
Thanks for your help

2024-05-01 10:34 UTC, iblowmymind commented
No problem! Glad I could help. I missed the breaks entry, thanks for pointing it out lol